---
title: "Something"
author: "Shrusti Ghela"
date: "7/13/2022"
output: pdf_document
---

```{r}
df = read.csv("~/Data.csv")
```

```{r}
df <- as.data.frame(df)
```

```{r}
lm.fit <- lm(b ~ Grain.size + Density, data=df)
summary(lm.fit)
plot(df$Grain.size, df$b)
plot(df$Density, df$b)

```
```{r}
df$pred <- 0.3120 + 0.2773*df$Grain.size + 4.0223*df$Density
```

```{r}
lm.fit.2 <- lm(b ~ poly(Grain.size, 2, raw=TRUE) + poly(Density, 2, raw=TRUE), data=df)
summary(lm.fit.2)
```
```{r}
df
```
```{r}
x <- df$Grain.size
y<- df$Density
z <- df$b

library("plot3D")

```
```{r}
fit <- lm(z ~ x + y)
```

```{r}
grid.lines = 40
x.pred <- seq(min(x), max(x), length.out = grid.lines)
y.pred <- seq(min(y), max(y), length.out = grid.lines)
xy <- expand.grid( x = x.pred, y = y.pred)
z.pred <- matrix(predict(fit, newdata = xy), 
                 nrow = grid.lines, ncol = grid.lines)
```

```{r}
fitpoints <- predict(fit)
```

```{r}
scatter3D(x, y, z, pch = 19, cex = 1,colvar = NULL, col="red", 
          theta = 10, phi = 180, bty="b",
          xlab = "Grain Size", ylab = "Density", zlab = "b",  
          surf = list(x = x.pred, y = y.pred, z = z.pred,  
                      facets = TRUE, fit = fitpoints, col=ramp.col (col = c("dodgerblue3","seagreen2"), n = 300, alpha=0.9), border="black"), main = "Plot")

```
```{r}
summary(fit)
```
```{r}
df$height <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
```

```{r}
lm.fit <- lm(b ~ Grain.size + Density +height, data=df)
```
```{r}
summary(lm.fit)
```
```{r}
df$pred2 <- predict(lm.fit)
```

```{r}
mean((df$b-df$pred)^2)
mean((df$b-df$pred2)^2)
```

